fixtures:
  repositories:
    concat: git://github.com/ripienaar/puppet-concat.git
    ruby: git://github.com/evenup/evenup-ruby.git
    sensu: gitolite://git.ineu.us:puppet/evenup-sensu
  symlinks:
    pdns: "#{source_dir}"

