fixtures:
  repositories:
    concat: git://github.com/ripienaar/puppet-concat.git
    ruby: git://github.com/evenup/evenup-ruby.git
    sensu: git://github.com/sensu/sensu-puppet.git
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
  symlinks:
    pdns: "#{source_dir}"

