fixtures:
  repositories:
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    ruby: https://github.com/evenup/evenup-ruby.git
    sensu: https://github.com/sensu/sensu-puppet.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
  symlinks:
    pdns: "#{source_dir}"

