name 'evenup-pdns'
version '1.2.0'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
summary 'Installs PowerDNS and PuppetDB backend'
description 'Installs PowerDNS both authorative and recursor and a PuppetDB pipe backend for forward and reverse lookups of nodes in PuppetDB'
project_page 'https://github.com/evenup/evenup-pdns'
dependency 'puppetlabs/concat'
dependency 'evenup/ruby', '>= 1.3.3'
