name 'evenup-pdns'
version '0.1.1'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
summary 'Installs PowerDNS and PuppetDB backend'
description 'Installs PowerDNS both authorative and recursor and a PuppetDB pipe backend for forward and reverse lookups of nodes in PuppetDB'
source 'https://github.com/evenup/evenup-pdns'
project_page 'https://github.com/evenup/evenup-pdns'
dependency 'ripienaar/concat', '>= 0.2.0'
dependency 'evenup-ruby', '>= 1.3.3'
